export const presets = {
  '1': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'None',
    gravity: 'center',
    zoom: 1,
    effect: 'none',
    blurFace: 'none',
    vignette: false,
    cartoonify: false,
    text: 'none',
    watermark: 'none',
    name: 'Default',
  },
  '2': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'max',
    gravity: 'none',
    zoom: 1,
    effect: 'grayscale',
    blurFace: 'none',
    vignette: false,
    cartoonify: false,
    text: 'none',
    watermark: 'none',
    name: 'Rundt bilde + svart/hvit',
  },
  '3': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'max',
    gravity: 'none',
    zoom: 1,
    effect: 'none',
    blurFace: 'none',
    vignette: false,
    cartoonify: false,
    text: 'none',
    watermark: 'none',
    name: 'Rundt bilde',
  },
  '4': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'None',
    gravity: 'center',
    zoom: 1,
    effect: 'none',
    blurFace: 'e_blur_faces:1000',
    vignette: false,
    cartoonify: false,
    text: 'none',
    watermark: 'none',
    name: 'Anonymiser ansikt i bilder',
  },
  '5': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'None',
    gravity: 'center',
    zoom: 1,
    effect: 'none',
    blurFace: 'none',
    vignette: true,
    cartoonify: false,
    text: 'none',
    watermark: 'none',
    name: 'Vignett',
  },
  '6': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'None',
    gravity: 'center',
    zoom: 1,
    effect: 'none',
    blurFace: 'none',
    vignette: false,
    cartoonify: true,
    text: 'none',
    watermark: 'none',
    name: 'Cartoonify',
  },
  '7': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'None',
    gravity: 'center',
    zoom: 1,
    effect: 'none',
    blurFace: 'none',
    vignette: false,
    cartoonify: false,
    text: 'l_text:Arial_45_bold:Hello World,g_south,co_orange,x_20,y_20',
    watermark: 'none',
    name: 'Tekst',
  },
/*  '8': {
    aspectRatio: 'none',
    width: 800,
    height: 800,
    radius: 'None',
    gravity: 'center',
    zoom: 'None',
    effect: 'none',
    blurFace: 'none',
    vignette: false,
    cartoonify: false,
    text: 'none',
    watermark: 'l_guru_dpzplt,o_30,g_south,x_20,y_20',
  },*/
  '8': {
    aspectRatio: 'none',
    width: 800,
    height: 500,
    radius: '150:0',
    gravity: 'center',
    zoom: 1,
    effect: 'none',
    blurFace: 'none',
    vignette: false,
    cartoonify: false,
    text: 'none',
    watermark: 'none',
    name: 'To runde hjørner',
  }
}